twig:
    paths: 
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/admin/templates'
    form_themes:    
        - 'bootstrap_5_layout.html.twig'    


when@test:
    twig:
        strict_variables: true
