controllers:
    resource: ../src/Controller/
    type: attribute

admin_routes:
    # loads routes from the YAML, XML or PHP files found in that directory
    resource: '../admin/config'
    type: directory

import_routes:
    # loads routes from the YAML, XML or PHP files found in that directory
    resource: '../import/config'
    type: directory
